{
 "title": "iptv机器性能监控平台",
 "description": "Streamline and optimize important metrics with Node Exporter v0.16+. Contains: CPU memory Disk IO network temperature and other monitoring indicators. https://github.com/starsliao/Prometheus translated by Google :-) ",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "主机名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   {
    "name": "node",
    "label": "服务节点ip",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "内存大小",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘总空间",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"}/1000/1000/1000",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "分时磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU核心数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_已使用内存"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_可用内存"
    }
   ]
  },
  {
   "title": "cpu使用率, 磁盘每秒io消耗率 (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_内核模式下cpu使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_用户模式下cpu使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_per 每秒io操作 %"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "磁盘io读写率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "iops", "label": "read（-）/write（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "upload（-）/download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in 下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out 上传"
    }
   ]
  },
  {
   "title": "磁盘io读写时间",
   "type": "graph",
   "description": "读取时间ms每个磁盘分区读取操作的秒数\n\n写入时间ms每个磁盘分区写入操作的秒数\n\nIO时间毫秒每个磁盘分区输入/输出操作花费的秒数\n\n每个磁盘分区输入/输出操作花费的IO时间加权秒数",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "read（-）/ write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写"
    }
   ]
  },
  {
   "title": "磁盘io读写容量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "read（-）/write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "tcp连接情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_已建立"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_ time wait"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  }
 ]
}